[workspace]
members = [
"00_blue", 
"01_triangle",
"02_square", 
"03_colour", 
"04_many", 
"05_rotate",
"06_image", 
"07_big", 
"08_grey", 
"09_blur", 
"10_mid", 
"11_scaler", 
"12_layer", 
"13_bright", 
"14_hue", 
"15_glitch", 
"16_water", 
"17_illuminate", 
"18_wallpaper", 
]

resolver = "3"
# [profile.release]
# opt-level="s"
# debug=false
# lto="thin"
# panic="abort"
# codegen-units=1
# strip="symbols"
